version: 0.0.{build}
build_script:
- cmd: |
    dotnet restore
    dotnet build CoreBootstrapLibrary
    dotnet pack CoreBootstrapLibrary
test_script:
- cmd: >
    dotnet test CoreBootstrapLibrary.Tests
artifacts:
- path: '**/*.nupkg'